name: Novel scraper testser for window

on:
  push:
    branches:
      - dev

jobs:
  test_script:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      - name: Install dependencies
        run: | 
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        run: python main.py > scrapit_test_logs.txt
        continue-on-error: true

      - name: Upload scrapit_test_logs by artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scrapit_test_logs
          path: scrapit_test_logs.txt
