name: Novel scraper testser for window

on:
  push:
    branches:
      - fix-issue-1

jobs:
  test_script:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        run: python -u main.py